apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-demo
  name: quarkus-demo
  namespace: default
spec:
  clusterIP: 172.30.216.115
  clusterIPs:
  - 172.30.216.115
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
  selector:
    app: quarkus-demo
