apiVersion: v1
data:
{{- $path := printf "config/%s/*.properties" .Values.environment }}
{{ (.Files.Glob  $path).AsConfig | indent 2 }}
kind: ConfigMap
metadata:
  name: application-configuration
  labels:
    {{ .Values.app.commonLabels | toYaml}}

