apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: development

configMapGenerator:
- behavior: merge
  files:
  - application-development.properties
  name: application-configuration

resources:
- namespace.yaml
- ../../base

namespace: kustomize-development

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: "QUARKUS_PROFILE"
        value: "development"
  target:
    kind: Deployment
    name: quarkus-demo

images:
- name: quay.io/jmayorgarh/quarkus-demo
  newTag: 1.0.0
