apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: production

configMapGenerator:
  - name: application-configuration
    behavior: merge
    files:
      - application-production.properties
resources:
  - namespace.yaml
  - ../../base

namespace: production

patches:
  - target:
      kind: Deployment
      name: quarkus-demo
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: "QUARKUS_PROFILE"
          value: "production"
