apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: application-configuration
    files:
      - application.properties

commonLabels:
  environment: base

resources:
  - 01-deployment.yaml
  - 02-service.yaml
  - 03-route.yaml
